// For https://community.bistudio.com/wiki/Spearhead_1944_AI_Systems_(AIS)#MissionNamespace_Variables

private _AISData =
[
	[
		"SPE_AIS_DebugSwitch_systemChat",
		"Enables debugging via [[systemChat| system chat]]. SPE_AIS_IFS_DebugSwitch needs to be set to [[true]] as well.",
		true
	],
	[
		"SPE_AIS_IFS_DebugSwitch",
		"Enables debugging. Needs to be set to true for all other debug modes to work.",
		false
	],
	[
		"SPE_AIS_Sides",
		"All affected sides.",
		[east, west, resistance]
	],
	[
		"SPE_AIS_cadetDifficulty",
		"Use cadet difficulty.",
		false
	],
	[
		"SPE_AISuiteLoopActive",
		"Is AIS main loop running. Set to [[false]] to disable.",
		true
	],
	[
		"SPE_Active_AISuite",
		"If set to [[false]] AI system will be paused.",
		true
	],
	[
		"SPE_Active_Flee",
		"Can groups flee?",
		true
	],
	[
		"SPE_Active_GroupTracing",
		"Group traces regardless of flee/surrender active",
		true
	],
	[
		"SPE_Active_InfoSharing",
		"Do groups share knowledege.",
		true
	],
	[
		"SPE_Active_Surrender",
		"Can units surrender?",
		true
	],
	[
		"SPE_Active_TweakAI",
		"Groups of AI can be tweaked",
		true
	],
	[
		"SPE_Active_TweakAI_rearm",
		"AI can rearm.",
		true
	],
	[
		"SPE_Active_Unstuck",
		"Enable unstuck system.",
		true
	],
	[
		"SPE_AddGroups",
		"Additional groups for AIS",
		[]
	],
	[
		"SPE_AffectOurSide",
		"Should ''good guys'' be affected by retreat/flee/surrender/POW/shock.",
		false
	],
	[
		"SPE_CleanUp_Distances",
		"clean up from player distances in format [retreat, fleeing, surrender]",
		"[((getObjectViewDistance select 0) + 20),((getObjectViewDistance select 0) + 20),-1]"
	],
	[
		"SPE_CleanUp_Hourglass",
		"Time in seconds that must pass from gaining non-combatant status to the moment, when non-combatant can be cleaned up in format [minimum time, max random addition]. Final value is determined at gaining non-combatant status.",
		[120,240]
	],
	[
		"SPE_CleanUp_PlayableObservers",
		"Use playable/switchable units instead of current player units to check, if any player is too close to clean up non-combatants",
		false
	],
	[
		"SPE_CrowdPsyche",
		"Other's Retreat/Flee/Surrender behaviour affect my behaviour.",
		false
	],
	[
		"SPE_Cycle_Flee",
		"flee check interval in seconds",
		5
	],
	[
		"SPE_Cycle_InfoSharing",
		"info share interval in seconds",
		5
	],
	[
		"SPE_Cycle_Surrender",
		"surrender check interval in seconds",
		2
	],
	[
		"SPE_Cycle_TweakAI",
		"AI tweak interval in seconds",
		1
	],
	[
		"SPE_Cycle_Unstuck",
		"unstuck interval in seconds",
		10
	],
	[
		"SPE_FleeThreshold",
		"Flee threshold [5,50,100]",
		[5,50,100]
	],
	[
		"SPE_GlobalStressMultiplier",
		"basic stress multiplier",
		1
	],
	[
		"SPE_GlobalThreatMultiplier",
		"threat multiplier",
		1
	],
	[
		"SPE_InfoShare_BoostedInfoValue",
		"Info share boosted info value",
		3.5
	],
	[
		"SPE_InfoShare_maxTargetDistance_forInfantry",
		"Info share max distance from the revealed target if receiver is an infantry",
		300
	],
	[
		"SPE_InfoShare_maxTargetDistance_forInfantry_boosted",
		"Info share max distance from the revealed target if receiver is an infantry (knowledge boost)",
		150
	],
	[
		"SPE_InfoShare_maxTargetDistance_forVehicle",
		"Info share max distance from the revealed target if receiver is a vehicle",
		150
	],
	[
		"SPE_InfoShare_maxTargetDistance_forVehicle_boosted",
		"Info share max distance from the revealed target if receiver is a vehicle (knowledge boost)",
		50
	],
	[
		"SPE_InfoShare_revealCapMaximum",
		"Maximal reveal value",
		3.5
	],
	[
		"SPE_InfoSharing_Range",
		"How far AI units can share information.",
		[0, (1500 min (getObjectViewDistance select 0))]
	],
	[
		"SPE_InfoSharing_ReceivingRange",
		"How far receiver may get radio info ([east, west, resistance, other]).",
		[500, 500, 500, 500]
	],
	[
		"SPE_LocalDebug",
		"Player-local debug. By default disabled in multiplayer.",
		"!isMultiplayer"
	],
	[
		"SPE_LocalDebug_fadeOut",
		"Player-local debug fade out delay (if applicable - permanent icons excluded).",
		10
	],
	[
		"SPE_MHILoopPause",
		"As log this is [[true]], anti-road collisions component will be paused.",
		false
	],
	[
		"SPE_MHILoopSwitch",
		"If [[false]], anti-road collisions component will cease to work permanently.",
		false
	],
	[
		"SPE_MoraleAffectingTargetsRange",
		"Farther groups are ignored as a threat source",
		100
	],
	[
		"SPE_OurSide",
		"Our side, the ''good'' guys.",
		resistance
	],
	[
		"SPE_PlayerStressMultiplier",
		"Players are scarier than AI units.",
		1.5
	],
	[
		"SPE_RFSThresholds_ATStressDivisor",
		"Must be positive number. The higher, the more being AT-capable reduces stress generated by armored threats (it is already somewhat lower for this equal to 1).",
		2
	],
	[
		"SPE_RFSThresholds_MultiplierRF",
		"The lower, the easier for retreat/flee",
		1
	],
	[
		"SPE_RFSThresholds_MultiplierS",
		"The lower, the easier for surrender",
		1
	],
	[
		"SPE_RFS_POWWalkTimer",
		"Surrendered will automtically walk as POWs after that amount of seconds + 2-5s.",
		60
	],
	[
		"SPE_ReliableEmbarking",
		"Enabling reliable embarking assistance for groups of included sides",
		[east,west,resistance,civilian]
	],
	[
		"SPE_RetreatFollowUp",
		"Optional sets of custom follow-up behavior codes after disengage stage of retreat routine is completed. Each side array in selectRandomWeighted-ready format: [string,probability]. Code must be finite, otherwise group will be considered in retreating state indefinitely.",
		[[],[],[],[]]
	],
	[
		"SPE_RetreatPositions",
		"Optional sets of positions, towards which retreating groups should move per side. Each side array in selectRandomWeighted-ready format: [coordinates,probability]. Example: [[500,1500,0],0.25,(getMarkerPos 'marker1'),0.75].",
		[[],[],[],[]]
	],
	[
		"SPE_RetreatTime",
		"Duration in seconds of disengage stage in retreat routine in format [minimum time, max random addition]. Unlimited (by default) when result is negative.",
		[-1, 0]
	],
	[
		"SPE_StressDifficultyComponentDivisor",
		"The lower, the bigger impact on group's stress has game difficulty setting values below 1.5 are treated as 1.5.",
		3
	],
	[
		"SPE_SurrenderThreshold",
		"Surrender threshold",
		[90,150,200]
	],
	[
		"SPE_ThreatProximityMultiplier",
		"Decides, by how much threat source distance reduces generated threat. values below 1 amplify influence of distance down to 0.001, which basically nullifies the threat at any distance. values above 1 reduce that influence, so farther hostiles would be more threatening.",
		1
	],
	[
		"SPE_UnstuckExcluded",
		"Units excluded from unstucking",
		[]
	],
	[
		"SPE_UnstuckHideTerrainObjects",
		"which types of terrain objects can be hidden by unstuck component:<br />* 1: ['TREE','SMALL TREE','BUSH','FOREST','HIDE','FENCE','WALL'] - Can hide near stuck vehicles when player observer within 200m<br />* 2: ['TREE','SMALL TREE','BUSH','FOREST','HIDE','FENCE','WALL'],//,'HOUSE','BUILDING','BUNKER'] - Can hide near stuck vehicles if no player observer in 200m<br />* 3: ['TREE','BUSH','FOREST','WALL'] - 'blocking foliage' to hide in front of a stuck vehicle<br />* 4: ['river','pond'] - Don't hide blacklist per substrings present in the terrain object name string (str object), case-insensitive, probably best to keep it short due to performance impact (numerous string comparisons)",
		[[], [], [], []]
	],
	[
		"SPE_Unstuck_BBMoveAside",
		"Should bounding box based move aside empty vehicles unstuck feature be active per side: [west,east,resistance,other]",
		[true,true,true,true]
	],
	[
		"SPE_Unstuck_EPEMoveAside",
		"Should EPE-contact move aside not moving vehicles unstuck feature be active per side: [west,east,resistance,other]",
		[true,true,true,true]
	],
	[
		"SPE_Unstuck_GroupsToCheck",
		"Additional groups to be checked by the unstuck system.",
		[]
	],
	[
		"SPE_Unstuck_HiddenOnly",
		"Unstuck not in player's sight",
		false
	],
	[
		"SPE_Unstuck_MoveAsideNonHostilesOnly",
		"Should unstuck move aside obstacles only if non hostile",
		true
	],
	[
		"SPE_Unstuck_MoveAsideRoadOnlyObstacle",
		"Should unstuck move aside obstacles only from the road",
		true
	],
	[
		"SPE_Unstuck_MoveAsideRoadOnlyVehicle",
		"Should unstuck move aside obstacles only, if vehicle moves on the road",
		true
	],
	[
		"SPE_Unstuck_MoveAsideTanksByTanksOnly",
		"Should tank kind obstacles be moved aside only by other tanks",
		true
	],
	[
		"SPE_addSpawnedGroups",
		"Spawned groups added to AIS. '''Currently has no effect for Zeus-spawned units.",
		true
	],
	[
		"SPE_additionalPrimaryWeaponAmmoForAI",
		"Additional primary weapon ammo for all AIs out there.",
		"if (SPE_AIS_cadetDifficulty) then {6} else {0}"
	],
	[
		"SPE_doCatchUp",
		"Group members movement speed manipulation to improve group cohesion on the move",
		true
	],
	[
		"SPE_doDiamondInCombat",
		"Switch groups formations to DIAMOND when in combat. Can improve AI navigation over the terrain.",
		true
	],
	[
		"SPE_doHandleBlockingStuff",
		"should unstuck try to hide various map objects around the stuck vehicles",
		true
	],
	[
		"SPE_doHideBlockingFoliage",
		"should unstuck try to hide blocking foliage objects in front of stuck vehicles",
		true
	],
	[
		"SPE_doLeaveFootmobilesBehind",
		"Leave behind in separate group redundant tank crewmen",
		true
	],
	[
		"SPE_doManTurrets",
		"Important empty vehicle seats may be manned by passengers",
		true
	],
	[
		"SPE_doReliableEmbarking",
		"Improved reliability of embarking vehicles especially in combat situations",
		true
	],
	[
		"SPE_doTweakDisembarkInCombat",
		"Tweaked rules of disembarking passengers from vehicle in combat",
		false
	],
	[
		"SPE_mobilityRepairTime",
		"How long it takes to restore vehicle's mobility when all conditions are met in seconds. 0 to repair as soon conditions are met.",
		0
	],
	[
		"SPE_nonCombatantKillsAllowed",
		"Can fleeing, surrendering or POW units be killed.",
		false
	],
	[
		"SPE_permanentShockProb",
		"Permanent shock probability",
		0.1
	]
];

_AISData = [_AISData, [], { _x#0 }, "ASCEND"] call BIS_fnc_sortBy;

private _text = "= MissionNamespace Variables =" + endl;

{
	_x params ["_varName", "_description", "_value"];

	private _dataType = typeName _value;

	_dataType = switch _dataType do
	{
		case "ARRAY": {"Array"};
		case "STRING": {"String"};
		case "SCALAR": {"Number"};
		case "HASHMAP": {"HashMap"};
		case "SCRIPT": {"Script"};
		case "CODE": {"Code"};
		case "BOOL": {"Boolean"};
		default
		{
			toUpper (_dataType select [0, 1]) + toLower (_dataType select [1])
		};
	};

	_description = (toUpper (_description select [0,1]) + _description select [1]);

	if !(_description select [count _description - 1] in [".", "?"]) then
	{
		_description = _description + ".";
	};

	_text = _text + format ["== %1 ==", _varName] + endl;
	_text = _text + format ["'''Data Type: '''[[%1]]", _dataType] + endl + endl;
	_text = _text + "'''Locality:''' {{Icon|globalEffect|24}}" + endl + endl;
	_text = _text + "'''Default Value:'''" + format ["<sqf inline>%1</sqf>", _value] + endl + endl;
	_text = _text + format ["'''Description:''' %1", _description] + endl;
} forEach _AISData;

_text = _text + endl + endl + "[[Category: Spearhead 1944]]";

copyToClipboard _text;